grpc:
  server:
    port: 3501


spring:
  application:
    name: configclient
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      keys: [orderId1 ,orderId2,test]
      storename: configstore

